import { StyleSheet } from 'react-native';

export const authColors = {
  background: '#FBFAF8',
  surface: '#FFFFFF',
  border: '#E8E1DA',
  text: '#221B17',
  textMuted: '#706660',
  textSoft: '#A1978F',
  primary: '#F55445',
  primaryPressed: '#DE4739',
};

export const authSharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: authColors.background,
  },
  keyboardAvoiding: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 34,
  },
  brand: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    color: authColors.primary,
    letterSpacing: 0,
  },
  title: {
    textAlign: 'center',
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '800',
    color: authColors.text,
    letterSpacing: 0,
    marginTop: 2,
  },
  subtitle: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 15,
    lineHeight: 22,
    color: authColors.textMuted,
    paddingHorizontal: 18,
  },
  formCard: {
    marginTop: 14,
    backgroundColor: authColors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: authColors.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#20150E',
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  fieldWrap: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: authColors.border,
    backgroundColor: authColors.surface,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  fieldIcon: {
    width: 26,
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 22,
    color: '#9A9088',
  },
  input: {
    flex: 1,
    fontSize: 17,
    lineHeight: 22,
    color: authColors.text,
    paddingVertical: 0,
  },
  eyeText: {
    fontSize: 17,
    lineHeight: 20,
    color: '#9A9088',
    fontWeight: '600',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginTop: 2,
    marginBottom: 18,
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#BFB6AE',
    backgroundColor: authColors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  checkboxChecked: {
    borderColor: authColors.primary,
    backgroundColor: '#FFF0ED',
  },
  checkboxTick: {
    color: authColors.primary,
    fontSize: 14,
    lineHeight: 14,
    fontWeight: '800',
  },
  checkboxText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 23,
    color: authColors.text,
  },
  linkText: {
    color: authColors.primary,
    fontWeight: '700',
  },
  primaryButton: {
    minHeight: 60,
    borderRadius: 18,
    backgroundColor: authColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: authColors.primary,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  primaryButtonPressed: {
    backgroundColor: authColors.primaryPressed,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonLabel: {
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  bottomLinkRow: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  bottomLinkText: {
    fontSize: 16,
    lineHeight: 20,
    color: authColors.textMuted,
  },
  bottomLinkAction: {
    fontSize: 16,
    lineHeight: 20,
    color: authColors.primary,
    fontWeight: '700',
  },
  errorText: {
    marginTop: -4,
    marginBottom: 12,
    fontSize: 13,
    lineHeight: 18,
    color: '#B84B40',
  },
});
